// Category List Users
export const POST_LOGIN_USER_REQUEST = "POST_LOGIN_USER_REQUEST";
export const POST_LOGIN_USER_SUCCESS = "POST_LOGIN_USER_SUCCESS";
export const POST_LOGIN_USER_FAILURE = "POST_LOGIN_USER_FAILURE";
