// Category Post
export const USER_AUTO_LOGIN_REQUEST = "USER_AUTO_LOGIN_REQUEST";
export const USER_AUTO_LOGIN_SUCCESS = "USER_AUTO_LOGIN_SUCCESS";
export const USER_AUTO_LOGIN_FAILURE = "USER_AUTO_LOGIN_FAILURE";
