// Category Post
export const ADD_POST_CATEGORY_REQUEST = "ADD_POST_CATEGORY_REQUEST";
export const ADD_POST_CATEGORY_SUCCESS = "ADD_POST_CATEGORY_SUCCESS";
export const ADD_POST_CATEGORY_FAILURE = "ADD_POST_CATEGORY_FAILURE";
