// Category List Users
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
// Category Post
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";
//Post Get Category List
export const GET_POST_CATEGORY_REQUEST = "GET_POST_CATEGORY_REQUEST";
export const GET_POST_CATEGORY_SUCCESS = "GET_POST_CATEGORY_SUCCESS";
export const GET_POST_CATEGORY_FAILURE = "GET_POST_CATEGORY_FAILURE";
//Post Category Post
export const POST_CATEGORY_REQUEST = "POST_CATEGORY_REQUEST";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_FAILURE = "POST_CATEGORY_FAILURE";