// Category Post
export const ADD_MEMBER_REGISTER = "ADD_MEMBER_REGISTER";
export const ADD_MEMBER_REGISTER_SUCCESS = "ADD_MEMBER_REGISTER_SUCCESS";
export const ADD_MEMBER_REGISTER_FAILURE = "ADD_MEMBER_REGISTER_FAILURE";
